apiVersion: v1
entries:
  seaweedfs-csi-driver:
  - apiVersion: v2
    appVersion: latest
    created: "2026-02-17T01:18:54.952051833Z"
    description: A Helm chart for Kubernetes CSI backed by a SeaweedFS cluster
    digest: fcea08da3506ecaa466dfb0fc07778f91ed93f84206311cd3405be4cb42f5367
    name: seaweedfs-csi-driver
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-csi-driver/helm/seaweedfs-csi-driver-0.2.10.tgz
    version: 0.2.10
  - apiVersion: v2
    appVersion: latest
    created: "2026-02-03T05:11:02.38637496Z"
    description: A Helm chart for Kubernetes CSI backed by a SeaweedFS cluster
    digest: 178522456771aee759e04e6802db66b5f58a2cf07cd5c7b05fc6d7e5c28c7265
    name: seaweedfs-csi-driver
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-csi-driver/helm/seaweedfs-csi-driver-0.2.9.tgz
    version: 0.2.9
  - apiVersion: v2
    appVersion: latest
    created: "2026-01-18T23:58:30.162429673Z"
    description: A Helm chart for Kubernetes CSI backed by a SeaweedFS cluster
    digest: 6c1531e5ee6bee31030f246e3a4b16e6dc94338a072687769dc6f2a95f596da4
    name: seaweedfs-csi-driver
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-csi-driver/helm/seaweedfs-csi-driver-0.2.8.tgz
    version: 0.2.8
  - apiVersion: v2
    appVersion: latest
    created: "2026-01-10T20:24:12.770743067Z"
    description: A Helm chart for Kubernetes CSI backed by a SeaweedFS cluster
    digest: a4ac2d737e698c3715e64cb3bc780e1735e75275d20fdc5ba9bc09cb71de892d
    name: seaweedfs-csi-driver
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-csi-driver/helm/seaweedfs-csi-driver-0.2.7.tgz
    version: 0.2.7
  - apiVersion: v2
    appVersion: latest
    created: "2026-01-02T04:52:36.107137884Z"
    description: A Helm chart for Kubernetes CSI backed by a SeaweedFS cluster
    digest: f8765a5bbe2d09ac24471615bc7e4c3c039d6b87440aa4d1087b71a54a6732f4
    name: seaweedfs-csi-driver
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-csi-driver/helm/seaweedfs-csi-driver-0.2.6.tgz
    version: 0.2.6
  - apiVersion: v2
    appVersion: latest
    created: "2025-12-23T19:23:07.165593833Z"
    description: A Helm chart for Kubernetes CSI backed by a SeaweedFS cluster
    digest: 9363dd88d00810aa55e0beb55a56b6c5328ca3e5d2f56a3b316c46431b8a4da6
    name: seaweedfs-csi-driver
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-csi-driver/helm/seaweedfs-csi-driver-0.2.5.tgz
    version: 0.2.5
  - apiVersion: v2
    appVersion: latest
    created: "2025-12-18T06:53:19.358597474Z"
    description: A Helm chart for Kubernetes CSI backed by a SeaweedFS cluster
    digest: ee970ee3aca9d6f25052312df1b672b566e4e5a3d1975096658cb52fd998a294
    name: seaweedfs-csi-driver
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-csi-driver/helm/seaweedfs-csi-driver-0.2.4.tgz
    version: 0.2.4
  - apiVersion: v2
    appVersion: latest
    created: "2025-12-07T02:58:49.37415916Z"
    description: A Helm chart for Kubernetes CSI backed by a SeaweedFS cluster
    digest: f6f920a5fc20cc253cfb98bada7b35ebcfa1ab17b3ee903807c82fb3c04e23d2
    name: seaweedfs-csi-driver
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-csi-driver/helm/seaweedfs-csi-driver-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: latest
    created: "2025-06-16T03:55:31.936224528Z"
    description: A Helm chart for Kubernetes CSI backed by a SeaweedFS cluster
    digest: 1ce8cea113b912645ed188496750b5f8231ab3da771d59f201a23e0a8ceb7036
    name: seaweedfs-csi-driver
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-csi-driver/helm/seaweedfs-csi-driver-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: latest
    created: "2024-01-24T17:21:10.072243502Z"
    description: A Helm chart for Kubernetes CSI backed by a SeaweedFS cluster
    digest: 10baa02a837bf9fa4a71b4846132225b63faf26553ac79a4f1050673325a66b4
    name: seaweedfs-csi-driver
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-csi-driver/helm/seaweedfs-csi-driver-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: latest
    created: "2023-07-24T06:56:16.822716919Z"
    description: A Helm chart for Kubernetes CSI backed by a SeaweedFS cluster
    digest: 59d9e982a1611edf88f36be981864db7144073ddcf628d2a8c380027f36fe002
    name: seaweedfs-csi-driver
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-csi-driver/helm/seaweedfs-csi-driver-0.1.3.tgz
    version: 0.1.3
generated: "2026-02-17T01:18:54.950864358Z"
