apiVersion: v1
entries:
  seaweedfs-csi-driver:
  - apiVersion: v2
    appVersion: latest
    created: "2025-11-03T06:19:41.895962399Z"
    description: A Helm chart for Kubernetes CSI backed by a SeaweedFS cluster
    digest: d70055ffff39a9c4d17b6ef77d2a3f5f9ab46b36b7e32fc18287c959a5f02588
    name: seaweedfs-csi-driver
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-csi-driver/helm/seaweedfs-csi-driver-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: latest
    created: "2025-06-16T03:55:31.936224528Z"
    description: A Helm chart for Kubernetes CSI backed by a SeaweedFS cluster
    digest: 1ce8cea113b912645ed188496750b5f8231ab3da771d59f201a23e0a8ceb7036
    name: seaweedfs-csi-driver
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-csi-driver/helm/seaweedfs-csi-driver-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: latest
    created: "2024-01-24T17:21:10.072243502Z"
    description: A Helm chart for Kubernetes CSI backed by a SeaweedFS cluster
    digest: 10baa02a837bf9fa4a71b4846132225b63faf26553ac79a4f1050673325a66b4
    name: seaweedfs-csi-driver
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-csi-driver/helm/seaweedfs-csi-driver-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: latest
    created: "2023-07-24T06:56:16.822716919Z"
    description: A Helm chart for Kubernetes CSI backed by a SeaweedFS cluster
    digest: 59d9e982a1611edf88f36be981864db7144073ddcf628d2a8c380027f36fe002
    name: seaweedfs-csi-driver
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-csi-driver/helm/seaweedfs-csi-driver-0.1.3.tgz
    version: 0.1.3
generated: "2025-11-03T06:19:41.895257372Z"
