name: dev Docker images

on:
  push:
    branches: [master]

  # Build on PR
  pull_request:

  # Allow trigger for external PRs
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: |
            chrislusf/seaweedfs-csi-driver
          tags: |
            type=raw,value=dev
          flavor: |
            latest=true
          labels: |
            org.opencontainers.image.title=seaweedfs-csi-driver
            org.opencontainers.image.description=SeaweedFS is a distributed storage system for blobs, objects, files, and data lake, to store and serve billions of files fast!
            org.opencontainers.image.vendor=Chris Lu

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get the current tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" | sed 's/\//_/g' >> $GITHUB_ENV

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: "--debug"

      - name: Login to DockerHub
        # if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v1
        with:
          # username: ${{ secrets.DOCKERHUB_USERNAME }}
          username: chrislusf
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        # if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          file: ./cmd/seaweedfs-csi-driver/Dockerfile
          platforms: linux/amd64, linux/arm, linux/arm64, linux/386
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
  helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Helm check
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ./deploy/helm/seaweedfs-csi-driver
          CHART_VALUES: ./deploy/helm/seaweedfs-csi-driver/values.yaml
