name: Build & release Docker images

on:
  push:
    branches:
      - "**"
    tags:
      - 'v*'
    paths:
      - 'cmd/seaweedfs-csi-driver/Dockerfile'
      - 'cmd/seaweedfs-csi-driver/*.go'
      - 'pkg/driver/**'
      - 'go.*'
      - '.github/**'

  # Build on PR
  pull_request:

  # Allow trigger for external PRs
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get the current tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" | sed 's/\//_/g' >> $GITHUB_ENV

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: "--debug"

      - name: Login to DockerHub
        # if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v1
        with:
          # username: ${{ secrets.DOCKERHUB_USERNAME }}
          username: chrislusf
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build
        # if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          file: ./cmd/seaweedfs-csi-driver/Dockerfile
          platforms: linux/amd64, linux/arm, linux/arm64, linux/386
          tags: latest
          labels: ${{ steps.docker_meta.outputs.labels }}
